CREATE TABLE [dbo].[Test]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Fname] VARCHAR(50) NULL, 
    [LName] VARCHAR(50) NULL, 
    [DateAdded] DATETIME NULL DEFAULT GETADATE(), 
    [DateModified] DATETIME NULL DEFAULT getdate()
)
